// bundled_fonts.cpp — see bundled_fonts.hpp.
//
// At build time `pulp_add_binary_data(pulp-bundled-fonts SOURCES …)` produces
// `pulp-bundled-fonts_data.hpp`, which declares one `extern const unsigned
// char <name>[]` + `<name>_size` per embedded asset. We mirror that list here
// so we can iterate over every bundled .ttf without scraping CMake state at
// runtime.
//
// Skia-dependent registration and lookup paths in this file are gated behind
// `PULP_HAS_SKIA`. Most non-Skia public stubs live in font_registry_stubs.cpp,
// alongside the Skia-independent text-boundary helpers; the generation
// read/bump stubs stay below because callers use them unconditionally.

#include <pulp/canvas/bundled_fonts.hpp>
#include <pulp/canvas/font_resolver.hpp>
#include <pulp/canvas/font_options.hpp>

#ifdef PULP_HAS_SKIA

#include <array>
#include <atomic>
#include <cctype>
#include <cstdlib>
#include <future>
#include <fstream>
#include <limits>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>
#include <vector>

#include "include/core/SkData.h"
#include "include/core/SkFontMgr.h"
#include "include/core/SkFontParameters.h"
#include "include/core/SkString.h"
#include "include/core/SkTypeface.h"

// Platform font manager used by the public `register_font` API so plugin
// authors can register .ttf/.otf bytes without callers injecting a manager.
// Keep this OS matrix as the single canvas-side source for CoreText,
// DirectWrite, Android, and fontconfig construction.
#if defined(__APPLE__)
#include "include/ports/SkFontMgr_mac_ct.h"
#elif defined(_WIN32)
#include "include/ports/SkTypeface_win.h"
#elif defined(__ANDROID__)
#include "include/ports/SkFontMgr_android.h"
#include "include/ports/SkFontScanner_FreeType.h"
#elif defined(__linux__)
#include "include/ports/SkFontMgr_fontconfig.h"
#include "include/ports/SkFontScanner_FreeType.h"
#endif

#include "pulp-bundled-fonts_data.hpp" // Generated by pulp_add_binary_data.

namespace pulp::canvas {

namespace {

struct BundledBlob {
    const char* asset_name;       // Original file name (for diagnostics).
    const unsigned char* data;
    std::size_t size;
};

// One entry per .ttf listed in core/canvas/CMakeLists.txt. Keep this list and
// the CMake SOURCES list in sync — there is intentionally no auto-discovery,
// so failures show up as a "file not declared" link error rather than a
// silent runtime miss.
const std::array<BundledBlob, 2>& bundled_blobs() {
    static const std::array<BundledBlob, 2> kBlobs = {{
        {"Inter-Regular.ttf",
         pulp_bundled_fonts::Inter_Regular_ttf,
         pulp_bundled_fonts::Inter_Regular_ttf_size},
        {"JetBrainsMono-Regular.ttf",
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf,
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf_size},
    }};
    return kBlobs;
}

// First call with a non-null `mgr` lazily materialises every blob into an
// SkTypeface keyed by the face's reported family name (NOT the file name —
// we trust Skia's name table parse over our naming convention). Lookup is
// O(1) average.
//
// The `mgr` argument is forwarded only on the initialising call; subsequent
// callers reuse the cache regardless of which font manager they hand in.
// We deliberately do NOT call `std::call_once` here: if the very first
// caller passes a null manager (e.g. a unit test that is verifying graceful
// degradation), `call_once` would burn the once-flag and the *next* caller
// with a real mgr would see an empty cache forever. Use a guard flag that
// only flips on success.
const std::unordered_map<std::string, sk_sp<SkTypeface>>&
ensure_registered(SkFontMgr* mgr) {
    static std::mutex lock;
    static bool initialized = false;
    static std::unordered_map<std::string, sk_sp<SkTypeface>> by_family;

    std::lock_guard<std::mutex> guard(lock);
    if (initialized || !mgr) return by_family;

    for (const auto& blob : bundled_blobs()) {
        if (!blob.data || blob.size == 0) continue;
        // SkData::MakeWithoutCopy is safe here: the array data has static
        // storage duration (lives for the entire process) and the
        // SkTypeface only holds a reference for as long as it's in our
        // cache, which is also static.
        auto sk_data = SkData::MakeWithoutCopy(blob.data, blob.size);
        sk_sp<SkTypeface> face = mgr->makeFromData(std::move(sk_data));
        if (!face) continue;

        SkString family;
        face->getFamilyName(&family);
        if (family.isEmpty()) continue;

        // First face wins for a given family. The bundle currently has at
        // most one face per family, so collisions just mean we shipped a
        // duplicate — keep the first deterministically.
        by_family.emplace(std::string(family.c_str()), std::move(face));
    }

    initialized = true;
    return by_family;
}

} // namespace

sk_sp<SkTypeface> match_bundled_typeface(SkFontMgr* mgr,
                                         const std::string& family,
                                         SkFontStyle style) {
    const auto& cache = ensure_registered(mgr);
    auto it = cache.find(family);
    if (it == cache.end()) return nullptr;

    // The bundle currently ships only Regular/Upright faces. If the caller
    // wants something else (bold, italic, ...) return nullptr so the
    // skia_canvas typeface lookup keeps walking and lets
    // SkFontMgr::matchFamilyStyle pick a system-installed bold/italic
    // variant. Otherwise bundled fonts would hijack off-style requests and
    // break CSS weight/slant matching.
    SkFontStyle have = it->second->fontStyle();
    if (have.weight() != style.weight() || have.slant() != style.slant()) {
        return nullptr;
    }
    return it->second;
}

std::size_t bundled_font_count() {
    return bundled_blobs().size();
}

// ── Plugin-registered font registry ──────────────────────────────────────
// Bundled fonts are baked in at build time and live forever in the binary;
// plugin-registered fonts come at runtime from `register_font(...)`. They
// share lookup mechanics (cache by family name, style-aware miss to keep
// weight/slant honouring intact) but live in a separate map so the bundled
// list stays canonical and we never accidentally drop a baked-in face when
// a plugin registers an overlapping family.

namespace {

// register_font is called per typeface, often once per weight/slant variant
// when a developer drops a folder full of TTFs. Keep every registered face per
// family so match_registered_typeface can pick the best style match instead of
// letting a later face silently replace an earlier one.
struct RegisteredEntry {
    std::vector<sk_sp<SkTypeface>> faces;
};

std::mutex& registered_mutex() {
    static std::mutex m;
    return m;
}

std::unordered_map<std::string, RegisteredEntry>& registered_fonts() {
    static std::unordered_map<std::string, RegisteredEntry> map;
    return map;
}

// Monotonic counter exposed via `font_registration_generation()`. Every
// successful mutation of process-global font state bumps it so downstream
// typeface caches (skia_canvas.cpp, text_shaper.cpp) can invalidate
// themselves on the next lookup. Atomic so callers don't need to hold the
// registration lock when probing.
std::atomic<std::uint64_t>& registration_generation() {
    static std::atomic<std::uint64_t> g{0};
    return g;
}

void bump_generation() noexcept {
    registration_generation().fetch_add(1, std::memory_order_acq_rel);
}

} // namespace

// Single canonical platform-font-manager helper, exported from
// `bundled_fonts.hpp`, so canvas/font code shares one OS switch for CoreText,
// DirectWrite, Android, and fontconfig managers.
sk_sp<SkFontMgr> platform_font_manager() {
    static sk_sp<SkFontMgr> mgr;
    static bool tried = false;
    if (!tried) {
        tried = true;
#if defined(__APPLE__)
        mgr = SkFontMgr_New_CoreText(nullptr);
#elif defined(_WIN32)
        mgr = SkFontMgr_New_DirectWrite();
#elif defined(__ANDROID__)
        mgr = SkFontMgr_New_Android(nullptr, SkFontScanner_Make_FreeType());
#elif defined(__linux__)
        mgr = SkFontMgr_New_FontConfig(nullptr, SkFontScanner_Make_FreeType());
#endif
    }
    return mgr;
}

bool face_wght_axis(const SkTypeface* face,
                    float& out_min, float& out_max, float& out_default) {
    if (!face) return false;
    // Query the axis count by passing an empty span (this Skia build's
    // getVariationDesignParameters returns the total axis count and only
    // fills as many as the span holds).
    const int count = face->getVariationDesignParameters(
        SkSpan<SkFontParameters::Variation::Axis>{});
    if (count <= 0) return false;  // static face (or query failed)
    std::vector<SkFontParameters::Variation::Axis> axes(
        static_cast<std::size_t>(count));
    if (face->getVariationDesignParameters(SkSpan(axes)) != count)
        return false;
    constexpr SkFourByteTag kWght = SkSetFourByteTag('w', 'g', 'h', 't');
    for (const auto& a : axes) {
        if (a.tag == kWght) {
            out_min = a.min;
            out_max = a.max;
            out_default = a.def;
            return true;
        }
    }
    return false;
}

sk_sp<SkTypeface> match_registered_typeface(const std::string& family,
                                            SkFontStyle style) {
    if (family.empty()) return nullptr;
    std::lock_guard<std::mutex> guard(registered_mutex());
    auto& map = registered_fonts();
    auto it = map.find(family);
    if (it == map.end() || it->second.faces.empty()) return nullptr;

    // Pass 1: exact match on weight + slant. This is the ideal path: caller
    // asked for Regular/Upright, a Regular/Upright is registered, hand it back
    // unchanged.
    for (const auto& f : it->second.faces) {
        if (!f) continue;
        SkFontStyle have = f->fontStyle();
        if (have.weight() == style.weight() && have.slant() == style.slant()) {
            return f;
        }
    }

    // Pass 2: best-effort closest match, but only within a tight tolerance.
    // Multi-face registrations should let a Regular request land on a nearby
    // family member such as SemiBold instead of forcing a system fallback that
    // loses Unicode coverage. An unbounded closest match overcorrects: a
    // family registered with only a Regular/Upright face would still satisfy a
    // Bold or Italic request, hijacking every weight/slant variant and masking
    // the real system Bold/Italic. Bound the heuristic to same-slant faces
    // within one approximate CSS weight step; genuinely off-style requests
    // return nullptr so the cascade keeps walking.
    constexpr int kMaxWeightGap = 200;
    sk_sp<SkTypeface> best;
    int best_gap = std::numeric_limits<int>::max();
    for (const auto& f : it->second.faces) {
        if (!f) continue;
        SkFontStyle have = f->fontStyle();
        if (have.slant() != style.slant()) continue;  // slant must match exactly
        int gap = std::abs(have.weight() - style.weight());
        if (gap > kMaxWeightGap) continue;             // weight too far off-style
        if (gap < best_gap) { best_gap = gap; best = f; }
    }
    if (best) return best;

    // Pass 3: variable-font weight eligibility.
    //
    // A registered variable font is stored as one typeface at its default
    // `wght` instance (e.g. Funnel Display defaults to 400). A request for
    // a far-off weight (700) fails passes 1-2 above because the static
    // weight gap (300) exceeds kMaxWeightGap. But the face can actually
    // RENDER 700 — its `wght` axis covers it. Rather than dropping to a
    // heavier system fallback (which loses the design's typeface entirely),
    // return the base variable face so the resolver can `makeClone` it at
    // the requested weight. Same slant is still required; the wght axis
    // only governs weight, not slant. Static faces are untouched (they have
    // no wght axis), so single-static-Regular families keep returning
    // nullptr for truly off-style requests.
    for (const auto& f : it->second.faces) {
        if (!f) continue;
        if (f->fontStyle().slant() != style.slant()) continue;
        float lo = 0, hi = 0, def = 0;
        if (face_wght_axis(f.get(), lo, hi, def)) return f;
    }
    return nullptr;
}

std::vector<RegisteredTypeface> registered_typefaces_snapshot() {
    std::vector<RegisteredTypeface> out;
    std::lock_guard<std::mutex> guard(registered_mutex());
    const auto& map = registered_fonts();
    for (const auto& [family, entry] : map) {
        for (const auto& f : entry.faces) {
            if (f) out.push_back({family, f});
        }
    }
    return out;
}

bool register_font(const std::uint8_t* data, std::size_t size,
                   const std::string& family_override) {
    if (!data || size == 0) return false;

    SkFontMgr* mgr = platform_font_manager().get();
    if (!mgr) {
        // No platform font manager → no way to materialise an SkTypeface
        // from raw bytes (the prebuilt Skia we ship doesn't link FreeType
        // standalone). Calling code should treat this as a soft failure.
        return false;
    }

    // SkData::MakeWithCopy so the caller can free `data` immediately. The
    // typeface owns the SkData reference for its full lifetime.
    auto sk_data = SkData::MakeWithCopy(data, size);
    sk_sp<SkTypeface> face = mgr->makeFromData(std::move(sk_data));
    if (!face) return false;

    std::string family = family_override;
    if (family.empty()) {
        SkString sk_family;
        face->getFamilyName(&sk_family);
        family.assign(sk_family.c_str());
    }
    if (family.empty()) {
        // Without a usable family name we have no key to register under —
        // refuse rather than insert under "".
        return false;
    }

    {
        std::lock_guard<std::mutex> guard(registered_mutex());
        // Append rather than overwrite. The lookup side picks the best style
        // match across all registered faces for this family. Idempotency: skip
        // if this exact typeface ptr is already present (same Skia identity),
        // but allow multiple physically-distinct faces (a Regular + Italic +
        // Bold trio is the normal case for "drop the font family folder in").
        auto& entry = registered_fonts()[family];
        bool dup = false;
        for (const auto& existing : entry.faces) {
            if (existing.get() == face.get()) { dup = true; break; }
        }
        if (!dup) entry.faces.push_back(std::move(face));
    }
    bump_generation();
    return true;
}

bool register_font_file(const std::string& path,
                        const std::string& family_override) {
    if (path.empty()) return false;
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file.is_open()) return false;
    std::streamsize size = file.tellg();
    if (size <= 0) return false;
    file.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> bytes(static_cast<std::size_t>(size));
    if (!file.read(reinterpret_cast<char*>(bytes.data()), size)) return false;
    return register_font(bytes.data(), bytes.size(), family_override);
}

namespace {

// Case-insensitive prefix match used for scheme detection. The URL grammar
// (RFC 3986 §3.1) is case-insensitive for the scheme, so "FILE://" must match
// "file://".
bool starts_with_ci(std::string_view value, std::string_view prefix) {
    if (value.size() < prefix.size()) return false;
    for (std::size_t i = 0; i < prefix.size(); ++i) {
        if (std::tolower(static_cast<unsigned char>(value[i])) !=
            std::tolower(static_cast<unsigned char>(prefix[i]))) return false;
    }
    return true;
}

// Strip a `file://` (or `file:`) scheme prefix and return the host-less
// absolute path. Empty result means the URL didn't carry a usable path.
std::string extract_file_path(const std::string& url) {
    constexpr std::string_view kFileScheme = "file://";
    constexpr std::string_view kFileBare   = "file:";
    if (starts_with_ci(url, kFileScheme)) {
        std::string rest = url.substr(kFileScheme.size());
        // file:// optionally carries a host: file://localhost/path or
        // file:///path. Drop everything up to the first slash that
        // begins the absolute path.
        if (!rest.empty() && rest.front() != '/') {
            auto slash = rest.find('/');
            if (slash == std::string::npos) return {};
            rest = rest.substr(slash);
        }
        return rest;
    }
    if (starts_with_ci(url, kFileBare)) {
        return url.substr(kFileBare.size());
    }
    return {};
}

} // namespace

std::future<FontState> register_font_url(const std::string& url,
                                         const std::string& family_override) {
    // HTTP(S): this API does not fetch network resources. Surface the
    // unsupported scheme as Failed so callers can branch on it without
    // blocking the main thread.
    if (starts_with_ci(url, "http://") || starts_with_ci(url, "https://")) {
        std::promise<FontState> p;
        p.set_value(FontState::Failed);
        return p.get_future();
    }

    // file:// or bare absolute path → schedule a real file read on a
    // background thread so plugin startup never blocks on disk I/O.
    std::string path = extract_file_path(url);
    if (path.empty()) {
        // Treat anything else with no scheme as a plain filesystem
        // path. Empty URL → Failed.
        if (url.empty()) {
            std::promise<FontState> p;
            p.set_value(FontState::Failed);
            return p.get_future();
        }
        path = url;
    }

    // `std::async(std::launch::async, ...)` returns a future whose destructor
    // blocks the caller until the task completes when the future is dropped
    // without `.get()` / `.wait()`. Use a promise + detached-thread pattern so
    // dropping the caller's future is genuinely non-blocking.
    auto promise = std::make_shared<std::promise<FontState>>();
    std::future<FontState> fut = promise->get_future();
    std::thread([promise, path = std::move(path), family_override]() mutable {
        // Wrap the whole worker body in a catch-all. `register_font_file()`
        // can throw (for example, a vector allocation backed by `tellg()` for
        // a huge or sparse file), and an exception escaping a detached thread
        // calls `std::terminate`. This API documents futures as safe to drop,
        // so convert every escape to `FontState::Failed`.
        FontState state = FontState::Failed;
        try {
            state = register_font_file(path, family_override)
                ? FontState::Loaded
                : FontState::Failed;
        } catch (...) {
            state = FontState::Failed;
        }
        try {
            promise->set_value(state);
        } catch (const std::future_error&) {
            // Promise already satisfied or abandoned — fine, we're a
            // detached worker. The caller's future is gone.
        }
    }).detach();
    return fut;
}

FontProbe probe_font_glyph(const std::string& family,
                           int weight, int slant,
                           std::uint32_t codepoint) {
    FontProbe out;
    out.family = family;
    out.codepoint = codepoint;
    out.requested_weight = weight;
    out.requested_slant = slant;

    if (family.empty()) return out;

    // Route through FontResolver so the probe sees exactly what fill_text
    // would resolve to. The resolver's cache is keyed on the full FontOptions
    // blob, so a probe call only pre-populates a key a subsequent real call
    // would have hit anyway.
    FontOptions opts;
    opts.family_stack.push_back(family);
    opts.weight = static_cast<float>(weight);
    opts.slant  = slant ? FontSlant::Italic : FontSlant::Normal;
    auto resolved = FontResolver::instance().resolve_family_list(opts);
    if (!resolved.typeface) return out;

    out.family_resolved = true;
    out.resolved_family = resolved.actual_family;
    out.origin = static_cast<std::uint8_t>(resolved.origin);
    out.registered_match = resolved.origin == FallbackOrigin::ScopeGlobal;
    const auto resolved_style = resolved.typeface->fontStyle();
    out.resolved_weight = resolved_style.weight();
    out.resolved_slant = resolved_style.slant() == SkFontStyle::kUpright_Slant ? 0 : 1;
    out.exact_style = out.resolved_weight == weight && out.resolved_slant == out.requested_slant;
    out.glyph_present = (resolved.typeface->unicharToGlyph(
        static_cast<SkUnichar>(codepoint)) != 0);
    return out;
}

bool is_font_registered(const std::string& family) {
    if (family.empty()) return false;
    std::lock_guard<std::mutex> guard(registered_mutex());
    auto& map = registered_fonts();
    return map.find(family) != map.end();
}

// WOFF2 runtime decoding.
//
// Pulp doesn't currently vendor Brotli or the Google `woff2` library,
// and the prebuilt Skia we ship is configured without its WOFF2
// converter exposed as a public symbol. That means the actual
// decompression step is gated on `__has_include(<woff2/decode.h>)` —
// if a downstream build vendors `external/woff2/` and links it into
// `pulp-canvas`, the real path lights up automatically; otherwise the
// surface stays at "structural-detect + fail cleanly", so callers can
// distinguish "not a WOFF2 file" from
// "WOFF2 file but no decoder linked" via `woff2_decoder_available()`.
//
// WOFF2 file signature is the 4-byte tag 'wOF2' = 0x77_4F_46_32 read
// big-endian at offset 0. See W3C WOFF2 §3, table 1.
namespace {
constexpr std::uint32_t kWoff2Magic = 0x774F4632u; // 'wOF2'
} // namespace

#if __has_include(<woff2/decode.h>)
#include <woff2/decode.h>
#define PULP_WOFF2_DECODER 1
#else
#define PULP_WOFF2_DECODER 0
#endif

bool woff2_decoder_available() noexcept {
#if PULP_WOFF2_DECODER
    return true;
#else
    return false;
#endif
}

bool register_font_woff2(const std::uint8_t* woff2_data, std::size_t size,
                         const std::string& family_override) {
    // Null or too-short to hold the 4-byte signature → not a WOFF2
    // file at all. Reject before we even probe the decoder so that
    // truncated/garbage input returns false on every build.
    if (!woff2_data || size < 4) return false;

    const std::uint32_t magic =
        (static_cast<std::uint32_t>(woff2_data[0]) << 24)
      | (static_cast<std::uint32_t>(woff2_data[1]) << 16)
      | (static_cast<std::uint32_t>(woff2_data[2]) <<  8)
      |  static_cast<std::uint32_t>(woff2_data[3]);
    if (magic != kWoff2Magic) return false;

#if PULP_WOFF2_DECODER
    // Real path: WOFF2 → sfnt → validator → register_font.
    //
    // The Google woff2 library exposes `ComputeWOFF2FinalSize` so we
    // can pre-size the output buffer, and `ConvertWOFF2ToTTF` for the
    // actual decompress. A WOFF2 header capping at 30MB is plenty for
    // any reasonable plugin font; reject anything larger to keep the
    // memory pressure bounded against hostile payloads. validate_font_bytes()
    // runs on the decompressed sfnt before we touch Skia.
    constexpr std::size_t kMaxDecompressed = 30u * 1024u * 1024u;
    std::size_t out_size = woff2::ComputeWOFF2FinalSize(woff2_data, size);
    if (out_size == 0 || out_size > kMaxDecompressed) return false;

    std::vector<std::uint8_t> sfnt(out_size);
    if (!woff2::ConvertWOFF2ToTTF(sfnt.data(), out_size, woff2_data, size)) {
        return false;
    }
    if (!validate_font_bytes(sfnt.data(), out_size)) return false;
    return register_font(sfnt.data(), out_size, family_override);
#else
    // No decoder linked. The bytes look like a WOFF2 file but we
    // cannot decompress them on this build. Caller should consult
    // `woff2_decoder_available()` and fall back to a pre-decoded
    // TTF/OTF via `register_font(...)`.
    (void)family_override;
    return false;
#endif
}

std::uint64_t font_registration_generation() noexcept {
    return registration_generation().load(std::memory_order_acquire);
}

void bump_font_registration_generation() noexcept {
    bump_generation();
}

// Structural TTF/OTF sanitizer. Validates the file header + table directory
// before handing bytes to Skia. Catches:
//   * truncated headers / files smaller than 12 bytes
//   * bad sfnt magic (not TTF / OTF / Mac TrueType / Type 1)
//   * malformed table directory (numTables claims more bytes than file
//     contains)
//   * out-of-bounds table entries (offset + length overflow file size)
//   * missing required tables (head, name, cmap, maxp)
//   * head table absent or too small to read its magic / version
//
// What this catches but per-table checksum verification doesn't:
// truncated tables, integer-overflow attempts in length fields,
// missing critical tables. A future per-table checksum gate can tighten this
// further; this structural pass rejects the practical attack surface a plugin
// developer would actually drop into `register_font`.

namespace {

inline std::uint16_t read_u16_be(const std::uint8_t* p) noexcept {
    return static_cast<std::uint16_t>((p[0] << 8) | p[1]);
}
inline std::uint32_t read_u32_be(const std::uint8_t* p) noexcept {
    return (static_cast<std::uint32_t>(p[0]) << 24)
         | (static_cast<std::uint32_t>(p[1]) << 16)
         | (static_cast<std::uint32_t>(p[2]) <<  8)
         |  static_cast<std::uint32_t>(p[3]);
}

inline bool is_valid_sfnt_magic(std::uint32_t magic) noexcept {
    return magic == 0x00010000u   // TrueType
        || magic == 0x4F54544Fu   // 'OTTO' — OpenType / CFF
        || magic == 0x74727565u   // 'true' — old Mac TrueType
        || magic == 0x74797031u;  // 'typ1' — PostScript Type 1
}

} // namespace

bool validate_font_bytes(const std::uint8_t* data, std::size_t size) {
    if (!data) return false;
    // sfnt header is 12 bytes (magic + numTables + searchRange +
    // entrySelector + rangeShift) — anything shorter is malformed.
    if (size < 12) return false;

    const std::uint32_t magic = read_u32_be(data);
    if (!is_valid_sfnt_magic(magic)) return false;

    const std::uint16_t num_tables = read_u16_be(data + 4);
    if (num_tables == 0) return false;

    // Table directory: each entry is 16 bytes (tag, checksum, offset,
    // length). Verify the directory itself fits in the file.
    const std::size_t dir_end = 12u + 16u * static_cast<std::size_t>(num_tables);
    if (dir_end > size) return false;

    // Required tables — names taken from the OpenType spec, presence
    // verified by tag scan. Absent any of these, Skia's downstream
    // parse will at best produce a degenerate typeface; reject early.
    constexpr std::uint32_t kHead = 0x68656164u; // 'head'
    constexpr std::uint32_t kName = 0x6E616D65u; // 'name'
    constexpr std::uint32_t kCmap = 0x636D6170u; // 'cmap'
    constexpr std::uint32_t kMaxp = 0x6D617870u; // 'maxp'
    // Presence is not enough: a malformed font can list required tables with
    // length=0 and still pass. Enforce minimum lengths derived from the
    // OpenType spec.
    //   head: 54 (full table)
    //   name: 6  (numNameRecords + storageOffset + format)
    //   cmap: 4  (version + numTables)
    //   maxp: 6  (version + numGlyphs)
    bool has_head = false, has_name = false, has_cmap = false, has_maxp = false;
    std::uint32_t head_offset = 0, head_length = 0;

    for (std::uint16_t i = 0; i < num_tables; ++i) {
        const std::uint8_t* entry = data + 12 + 16 * i;
        const std::uint32_t tag    = read_u32_be(entry);
        const std::uint32_t offset = read_u32_be(entry + 8);
        const std::uint32_t length = read_u32_be(entry + 12);
        // Out-of-bounds or overflow.
        if (offset > size) return false;
        if (length > size - offset) return false;
        if (tag == kHead) {
            if (length < 54) return false;
            has_head = true; head_offset = offset; head_length = length;
        } else if (tag == kName) {
            if (length < 6) return false;
            has_name = true;
        } else if (tag == kCmap) {
            if (length < 4) return false;
            has_cmap = true;
        } else if (tag == kMaxp) {
            if (length < 6) return false;
            has_maxp = true;
        }
    }
    if (!has_head || !has_name || !has_cmap || !has_maxp) return false;

    // The head table starts with a 4-byte major.minor version and a
    // 4-byte font revision, followed by the checksum-adjustment field
    // and the magic number 0x5F0F3CF5. A spec-conformant head is at
    // least 54 bytes; reject anything smaller as a structural fail.
    if (head_length < 54) return false;
    const std::uint8_t* head = data + head_offset;
    const std::uint32_t head_magic = read_u32_be(head + 12);
    if (head_magic != 0x5F0F3CF5u) return false;

    return true;
}

} // namespace pulp::canvas

#endif // PULP_HAS_SKIA

// Provide the no-Skia stubs so callers can read / bump the generation
// unconditionally. With no Skia the bump is a no-op (there's nothing
// downstream to invalidate) and the read always returns 0.
#ifndef PULP_HAS_SKIA
namespace pulp::canvas {
std::uint64_t font_registration_generation() noexcept { return 0; }
void bump_font_registration_generation() noexcept {}
} // namespace pulp::canvas
#endif
